# Pandas Functions

In [2]:
import pandas as pd

csv_1 = pd.read_csv("test.csv")

csv_1

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [3]:
csv_1.index

RangeIndex(start=0, stop=20, step=1)

In [4]:
csv_1.columns

Index(['Series_reference', 'Period', 'Data_value', 'Suppressed', 'STATUS',
       'UNITS', 'Magnitude', 'Subject', 'Group', 'Series_title_1',
       'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='object')

In [5]:
csv_1.describe()

           Period   Data_value  Suppressed  Magnitude  Series_title_5
count    20.00000    20.000000         0.0       20.0             0.0
mean   2006.32500  1447.018150         NaN        6.0             NaN
std       1.51001   170.956698         NaN        0.0             NaN
min    2004.06000  1146.156000         NaN        6.0             NaN
25%    2005.08250  1299.650500         NaN        6.0             NaN
50%    2006.10500  1449.599000         NaN        6.0             NaN
75%    2007.34750  1557.221500         NaN        6.0             NaN
max    2009.03000  1743.601000         NaN        6.0             NaN

In [7]:
csv_1.head(3)

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [8]:
csv_1.tail(4)

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [10]:
csv_1[6:12]

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [11]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [12]:
csv_1.index.array

<PandasArray>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Length: 20, dtype: int64

In [13]:
csv_1.to_numpy()

array([['SSSQ.SFMN1111CA', 2004.06, 1248.356, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2004.09, 1220.571, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2004.12, 1263.82, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.03, 1146.156, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.06, 1382.692, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.09, 1299.487, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.12, 1343.035, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.03, 1299.705, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.06, 1469.855, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.09, 1443.402, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.12, 1455.796, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.03, 1413.794, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.06, 1583.683, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.09, 1533.197, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.12, 1667.257, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.03, 1543.747, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.06, 1743.601, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.09, 1640.113, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.12, 1693.695, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2009.03, 1548.401, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan]],
      dtype=object)

In [15]:
import numpy as np

v = np.asarray(csv_1)

v

array([['SSSQ.SFMN1111CA', 2004.06, 1248.356, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2004.09, 1220.571, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2004.12, 1263.82, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.03, 1146.156, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.06, 1382.692, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.09, 1299.487, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2005.12, 1343.035, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.03, 1299.705, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.06, 1469.855, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.09, 1443.402, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2006.12, 1455.796, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.03, 1413.794, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.06, 1583.683, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.09, 1533.197, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2007.12, 1667.257, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.03, 1543.747, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.06, 1743.601, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.09, 1640.113, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2008.12, 1693.695, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan],
       ['SSSQ.SFMN1111CA', 2009.03, 1548.401, nan, 'F', 'dollars', 6,
        'Selected Services Survey (ANZSIC06) - SSS',
        'Industry sales - Subannual Financial Collection',
        'Scientific, Architectural and Engineering Services',
        'Sales (operating income)', 'Current prices', 'Actual', nan]],
      dtype=object)

In [16]:
csv_1.sort_index(axis=0,ascending=False)

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [18]:
csv_1["Period"][1]="Python"
csv_1

C:\Users\92333\AppData\Local\Temp\ipykernel_3912\3691530270.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_1["Period"][1]="Python"

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,Python,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [19]:
csv_1.loc[2,"Period"] = "Python"
csv_1

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,Python,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,Python,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [21]:
csv_1.loc[[2,3],["Period","UNITS"]]

    Period    UNITS
2   Python  dollars
3  2005.03  dollars

In [22]:
csv_1.loc[:,["Period","UNITS"]]

     Period    UNITS
0   2004.06  dollars
1    Python  dollars
2    Python  dollars
3   2005.03  dollars
4   2005.06  dollars
5   2005.09  dollars
6   2005.12  dollars
7   2006.03  dollars
8   2006.06  dollars
9   2006.09  dollars
10  2006.12  dollars
11  2007.03  dollars
12  2007.06  dollars
13  2007.09  dollars
14  2007.12  dollars
15  2008.03  dollars
16  2008.06  dollars
17  2008.09  dollars
18  2008.12  dollars
19  2009.03  dollars

In [26]:
csv_1.iloc[0:5,1:3]

    Period  Data_value
0  2004.06    1248.356
1   Python    1220.571
2   Python    1263.820
3  2005.03    1146.156
4  2005.06    1382.692

In [27]:
csv_1.drop("Period",axis=1)

,Series_reference,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN