# Read CSV Files
In this notebook we will explore different ways of reading a csv file while using different parameters and how can we manipulate it while reading.Some of the parameters used are:
- `nrows=`
- `usecols=[""]`
- `skiprows=`
- `index_col=`
- `header=`
- `names=[""]`
- `header=None,prefix=`

In [6]:
import pandas as pd                                                            #Importing Pandas

csv_1 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv")           #Reading CSV file

csv_1                                                                          #printing CSV file

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [9]:
csv_2 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",nrows=3)           #Reading CSV file with only top 3 rows

csv_2                                                                                  #priinting CSV file

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [12]:
csv_3 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",usecols=["Period","UNITS"]) #Reading CSV file with only 2 colmns

csv_3                                                                                           #printing CSV file

     Period    UNITS
0   2004.06  dollars
1   2004.09  dollars
2   2004.12  dollars
3   2005.03  dollars
4   2005.06  dollars
5   2005.09  dollars
6   2005.12  dollars
7   2006.03  dollars
8   2006.06  dollars
9   2006.09  dollars
10  2006.12  dollars
11  2007.03  dollars
12  2007.06  dollars
13  2007.09  dollars
14  2007.12  dollars
15  2008.03  dollars
16  2008.06  dollars
17  2008.09  dollars
18  2008.12  dollars
19  2009.03  dollars

In [15]:
csv_4 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",usecols=[1,5])   #Reading CSV file with only 2 cols using index

csv_4                                                                                #printing CSV file

     Period    UNITS
0   2004.06  dollars
1   2004.09  dollars
2   2004.12  dollars
3   2005.03  dollars
4   2005.06  dollars
5   2005.09  dollars
6   2005.12  dollars
7   2006.03  dollars
8   2006.06  dollars
9   2006.09  dollars
10  2006.12  dollars
11  2007.03  dollars
12  2007.06  dollars
13  2007.09  dollars
14  2007.12  dollars
15  2008.03  dollars
16  2008.06  dollars
17  2008.09  dollars
18  2008.12  dollars
19  2009.03  dollars

In [17]:
csv_4 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",skiprows=[0,3]) #Reading CSV file while skipping rows

csv_4                                                                               #printing CSV file

,SSSQ.SFMN1111CA,2004.06,1248.356,Unnamed: 3,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Services",Sales (operating income),Current prices,Actual,Unnamed: 13
0,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [18]:
csv_5 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",index_col="Period") #Reading CSV file while setting period col as index

csv_5                                                                                   #printing CSV file

,Series_reference,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
Period,,,,,,,,,,,,,
2004.06,SSSQ.SFMN1111CA,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2004.09,SSSQ.SFMN1111CA,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2004.12,SSSQ.SFMN1111CA,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2005.03,SSSQ.SFMN1111CA,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2005.06,SSSQ.SFMN1111CA,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2005.09,SSSQ.SFMN1111CA,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2005.12,SSSQ.SFMN1111CA,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2006.03,SSSQ.SFMN1111CA,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2006.06,SSSQ.SFMN1111CA,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2006.09,SSSQ.SFMN1111CA,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2006.12,SSSQ.SFMN1111CA,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2007.03,SSSQ.SFMN1111CA,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2007.06,SSSQ.SFMN1111CA,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2007.09,SSSQ.SFMN1111CA,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2007.12,SSSQ.SFMN1111CA,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2008.03,SSSQ.SFMN1111CA,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2008.06,SSSQ.SFMN1111CA,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2008.09,SSSQ.SFMN1111CA,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2008.12,SSSQ.SFMN1111CA,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2009.03,SSSQ.SFMN1111CA,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [19]:
csv_6 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",header=3) #Reading CSV file while setting row 3 as header

csv_6                                                                         #printing CSV file

,SSSQ.SFMN1111CA,2004.12,1263.82,Unnamed: 3,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Services",Sales (operating income),Current prices,Actual,Unnamed: 13
0,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [21]:
csv_7 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",names=["col1","col2","col3","col4",
                                                                           "col5","col6","col7","col8",
                                                                           "col9","col10","col11","col12",
                                                                           "col13","col14"]) #Reading CSV file while setting
                                                                                             #Header names using names parameter

csv_7                                                                                        #printing CSV file

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14
0,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
1,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2004.12,1263.82,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
20,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [22]:
csv_8 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",header=None, prefix = 'Col') #reading CSV file while changing header

csv_8                                                                                            #PRinting CSV file

C:\Users\92333\AppData\Local\Temp\ipykernel_13048\3258701883.py:1: FutureWarning: The prefix argument has been deprecated and will be removed in a future version. Use a list comprehension on the column names in the future.


  csv_8 = pd.read_csv("C:\\Users\\92333\\Documents\\Pandas\\test.csv",header=None, prefix = 'Col')

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,Col13
0,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
1,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2004.12,1263.82,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
20,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN